# Site settings
title: Opt-in Agile
email: gerardo.cepeda@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Opt-in Agile is a site with the mission of sharing empirical tested experiences and new trends in the Agile community.
   To help you and your teams to reach Mastery, Purpose and Autonomy in Lean, Kanban, Scrum, Scaling Agile ... as a
  result of iterative opt-in participation based experiments. Letting you and your people to choose and to be heard.
   Just because "having the choice" is always more fun.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http:/www.opt-inagile.org" # the base hostname & protocol for your site
twitter_username: gcepor
github_username:  gcporras

# Build settings
markdown: kramdown
